# Generated by Django 4.2.9 on 2024-02-15 11:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_yourself_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_yourself', models.CharField(max_length=500)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('date_of_birth', models.CharField(help_text='Ex : 1 Jan 2001 ', max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('degree', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=2)),
                ('website', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(help_text='Ex : 1 year 7 months', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('center_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='education_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('back_ground_image', models.ImageField(upload_to='mainbackground/')),
            ],
        ),
        migrations.CreateModel(
            name='professional_experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_experince_title', models.CharField(max_length=100)),
                ('professional_experince_duration', models.CharField(max_length=20)),
                ('professional_experince_detail', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(help_text='Ex : app or web', max_length=20)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_name', models.CharField(max_length=50)),
                ('project_overview', ckeditor.fields.RichTextField()),
                ('projectcategory', models.CharField(help_text='Ex : Application or Website', max_length=20)),
                ('clientname', models.CharField(max_length=20)),
                ('projectduration', models.CharField(help_text='Ex : Nov 2021 - Jun 2022', max_length=20)),
                ('projecturl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='skill_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('percentage', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='social_media_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.CharField(help_text='Ex : linkedin', max_length=40)),
                ('social_media_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projectimagefield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectimg', models.ImageField(upload_to='projectimg/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.project_detail')),
            ],
        ),
    ]
